# This file has been updated to deploy both Hosting and Functions.

name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          
      - name: Install Flutter dependencies and build web app
        run: |
          flutter pub get
          flutter build web

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BHAI_APP_HYDERBAIGG2 }}'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions Dependencies
        run: npm --prefix functions install
        
      - name: Deploy to Firebase
        run: firebase deploy --only hosting:bhai-app,functions --project=bhai-app-hyderbaigg2 --non-interactive --force
